#!/bin/bash

assembler="Assembler/assembler.py"

if [ -z $1 ];
then
    echo "Missing prog file."
    exit 1
else
    if ! [ -f $1 ];
    then
        echo "Could not find $1 at $PWD"
        exit 1
    fi
fi

if ! [ -f $assembler ];
then
    echo "Could not find assembler installation."
    exit 1
fi

if ! command -v python3 > /dev/null;
then
    echo "Could not find Python3 installation."
    exit 1
fi

if find . -maxdepth 1 -name "program.hex" > /dev/null;
then
    echo "Overwriting program.hex"
else
    echo "Creating program.hex"
fi

python3 "$assembler" < $1