#!/bin/bash

if [ -z $1 ];
then
    echo "Missing prog file."
    exit 1
else
    if ! [ -f $1 ];
    then
        echo "Could not find $1"
        exit 1
    fi
fi

if ! command -v python3 > /dev/null;
then
    echo "Could not find Python3 installation."
    exit 1
fi

if find . -name "program.hex" > /dev/null;
then
    echo "Overwriting program.hex"
else
    echo "Creating program.hex"
fi

python3 Assembler/assembler.py < $1