#!/bin/bash
all_project_files="ALU/alu.v Control/control.v \
                   DataMem/data_memory.v ForwardingUnit/fwdunit.v \
                   HazardDetect/hazard_detect.v ImmGen/immediate_gen.v \
                   InstrMem/instruction_memory.v RegisterBank/register_bank.v \
                   rv16r.v sim.v"
all_v_files=$(find ~/git/RISCV16 -name "*.v")
for f in $all_project_files; do
    if ! echo $all_v_files |  grep -q "$f";
    then
        echo "Missing $f from project."
        exit 1
    fi
done
IVLOG_VER=$(iverilog -V | sed -n '1p' | sed -r 's@^.*version ([0-9\.\-]+) .*$@\1@')
if ! [ -z $(echo "$IVLOG_VER <= 10.1" | bc -l) ];
then
    iverilog $all_v_files -Wall -s sim 2>&1 | grep -v ".*Port declaration of.*"
else
    iverilog $all_v_files -Wall -s sim
fi
vvp a.out
gtkwave my_dumpfile.vcd
